### ISSUE TITLE
RSS </link> missing

### ISSUE THREAD

**Issue by tillstuder** [oleeskild/digitalgarden#136]
I noticed the RSS feed is no longer working, when checking the file with VS Code I found the following problem:

![image](https://user-images.githubusercontent.com/11232144/233856870-38fb0b62-0a71-49c9-b558-bd13630b2a8b.png)

I assume this can be fixed by adding ´\</link>´ at the end of line 26 in `/src/site/feed.njk`

If you want to look at the `feed.xml` itself, it can ba accessed at: http://notes.tillstuder.com/feed.xml

**Comment by oleeskild** [comment]
Thanks for letting me know! Seems something changed in the latest version of 11ty. The link tags should be self-closing, i.e. <link href="..." />  . But it seems the self-closing tag was removed in the templating engine somewhere along the way. I've released a fix, that should make the rss feed work again 🤞

**Comment by tillstuder** [comment]
You are amazing! And suuuuuper fast to respond too!
P.S.: Can confirm, my feed is working again ❤️

**Comment by hdchieh** [comment]
> You are amazing! And suuuuuper fast to respond too! P.S.: Can confirm, my feed is working again ❤️

But when I access your feeds, the <link> is still not closed..

**Comment by gavmor** [comment]
Likewise, my `feed.xml` is still malformed, and so is @tillstuder's at https://notes.tillstuder.com/feed.xml: 
![image](https://github.com/user-attachments/assets/bc8200cd-6dfc-4a80-9b55-ff6e99007934)

**Comment by oleeskild** [comment]
This is such a weird bug, because it seem to re appear every now and then and for different people. The file in question, https://github.com/oleeskild/digitalgarden/blob/main/src/site/feed.njk, has closing tags in it. It even has several "/"s because for some reason that has helped in the past. (I've just assumed it was because of the character needed to be escaped or something). Those of you that have these problems, try to tweak that file and report back on what helped. Because I have to admit I have no idea where they disappear. 😅

**Comment by ArchEngel0** [comment]
Just popping in to say I bumped into that issue today and solved it in my instance via a combination of this issue thread and [this one](https://github.com/oleeskild/obsidian-digital-garden/issues/493). Turns out, 5 slashes, across every location that has backslashes (I had 3 locations I needed to change).
